# ReadTheDocs build config (aligned with py-libp2p).
# See https://docs.readthedocs.io/ and docs/readthedocs.rst for setup.
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - python -m pip install --upgrade pip
      - python -m pip install -e ".[docs,test]"
      # Generate api_reference toctree sources (modules.rst, dag.rst) before Sphinx runs
      - sphinx-apidoc -o docs dag

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .

formats:
  - epub
  - htmlzip
